version: "3.8"
services:
  client:
    image: node:lts
    ports:
      - "4400:4200"
    tty: true
    stdin_open: true
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - default
    command: "bash"